version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /MSFront
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: gomod
    directory: /Framework
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: gomod
    directory: /Proj/Example
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: /Proj/Example
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
