// Code generated by scripts/go-sdk.mjs; DO NOT EDIT.
// Source: docs/openapi/openapi.json
// Source SHA-256: bc6c75b84463fb7440ddb14538133717bb734f8fe670f5acbdecd12aa1bf03a5

package goexample

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"time"
)

const APIVersion = "1.4.0"
const DefaultMaxResponseBytes int64 = 1 << 20
const defaultSDKHTTPTimeout = 30 * time.Second
const defaultSDKConnectTimeout = 5 * time.Second
const defaultSDKResponseHeaderTimeout = 10 * time.Second
const defaultSDKIdleConnectionTimeout = 90 * time.Second
const defaultSDKMaxConnections = 100
const defaultSDKMaxIdleConnectionsPerHost = 10

var ErrResponseTooLarge = errors.New("goexample SDK response exceeds configured size limit")

var errInvalidHTTPResponse = errors.New("goexample SDK received an invalid HTTP response")

func preserveSDKRedirectResponse(_ *http.Request, _ []*http.Request) error {
	return http.ErrUseLastResponse
}

var defaultSDKHTTPTransport = &http.Transport{
	Proxy: http.ProxyFromEnvironment,
	DialContext: (&net.Dialer{
		Timeout:   defaultSDKConnectTimeout,
		KeepAlive: 30 * time.Second,
	}).DialContext,
	ForceAttemptHTTP2:      true,
	MaxIdleConns:           defaultSDKMaxConnections,
	MaxIdleConnsPerHost:    defaultSDKMaxIdleConnectionsPerHost,
	MaxConnsPerHost:        defaultSDKMaxConnections,
	IdleConnTimeout:        defaultSDKIdleConnectionTimeout,
	TLSHandshakeTimeout:    defaultSDKConnectTimeout,
	ExpectContinueTimeout:  time.Second,
	ResponseHeaderTimeout:  defaultSDKResponseHeaderTimeout,
	MaxResponseHeaderBytes: DefaultMaxResponseBytes,
}

var defaultSDKHTTPClient = &http.Client{
	Transport:     defaultSDKHTTPTransport,
	Timeout:       defaultSDKHTTPTimeout,
	CheckRedirect: preserveSDKRedirectResponse,
}

type HTTPClient interface {
	Do(*http.Request) (*http.Response, error)
}

type RequestEditorFn func(context.Context, *http.Request) error
type ClientOption func(*Client) error

type Client struct {
	baseURL          *url.URL
	httpClient       HTTPClient
	maxResponseBytes int64
	requestEditors   []RequestEditorFn
}

type Operation struct {
	OperationID string
	Method      string
	Path        string
	Deprecated  bool
}

var publishedOperations = [...]Operation{
	{OperationID: "getServiceIndex", Method: "GET", Path: "/", Deprecated: false},
	{OperationID: "getPrometheusMetrics", Method: "GET", Path: "/metrics", Deprecated: false},
	{OperationID: "getLiveness", Method: "GET", Path: "/livez", Deprecated: false},
	{OperationID: "getReadiness", Method: "GET", Path: "/readyz", Deprecated: false},
	{OperationID: "getStartup", Method: "GET", Path: "/startupz", Deprecated: false},
	{OperationID: "getApiLiveness", Method: "GET", Path: "/api/health", Deprecated: true},
	{OperationID: "getApiReadiness", Method: "GET", Path: "/api/health/ready", Deprecated: true},
	{OperationID: "getApiStartup", Method: "GET", Path: "/api/health/startup", Deprecated: true},
	{OperationID: "getSystemInfo", Method: "GET", Path: "/api/system/info", Deprecated: false},
	{OperationID: "login", Method: "POST", Path: "/api/v1/auth/login", Deprecated: false},
	{OperationID: "startOIDCBrowserAuthorization", Method: "GET", Path: "/api/v1/auth/oidc/start", Deprecated: false},
	{OperationID: "completeOIDCBrowserAuthorization", Method: "GET", Path: "/api/v1/auth/oidc/callback", Deprecated: false},
	{OperationID: "logoutOIDCBrowserSession", Method: "POST", Path: "/api/v1/auth/oidc/logout", Deprecated: false},
	{OperationID: "listOIDCBrowserSessions", Method: "GET", Path: "/api/v1/auth/oidc/sessions", Deprecated: false},
	{OperationID: "revokeAllOIDCBrowserSessions", Method: "DELETE", Path: "/api/v1/auth/oidc/sessions", Deprecated: false},
	{OperationID: "updateOIDCBrowserSessionDeviceName", Method: "PATCH", Path: "/api/v1/auth/oidc/sessions/{sessionId}", Deprecated: false},
	{OperationID: "revokeOIDCBrowserSession", Method: "DELETE", Path: "/api/v1/auth/oidc/sessions/{sessionId}", Deprecated: false},
	{OperationID: "getCurrentUser", Method: "GET", Path: "/api/v1/auth/me", Deprecated: false},
	{OperationID: "getHello", Method: "GET", Path: "/api/v1/example/hello", Deprecated: false},
	{OperationID: "postEcho", Method: "POST", Path: "/api/v1/example/echo", Deprecated: false},
	{OperationID: "validateProfile", Method: "POST", Path: "/api/v1/example/validate", Deprecated: false},
	{OperationID: "getDelayedResponse", Method: "GET", Path: "/api/v1/example/delay", Deprecated: false},
	{OperationID: "getPrivateExample", Method: "GET", Path: "/api/v1/example/private", Deprecated: false},
	{OperationID: "getProjectInfo", Method: "GET", Path: "/api/v1/project", Deprecated: false},
	{OperationID: "previewProject", Method: "GET", Path: "/api/v1/project/preview/{audience}", Deprecated: false},
	{OperationID: "describeProject", Method: "POST", Path: "/api/v1/project/describe", Deprecated: false},
}

type Response struct {
	StatusCode   int
	Header       http.Header
	Body         []byte
	HTTPResponse *http.Response
}

func completedSDKContextError(ctx context.Context) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	if deadline, ok := ctx.Deadline(); ok && !time.Now().Before(deadline) {
		return context.DeadlineExceeded
	}
	return nil
}

func closeSDKRequestBody(request *http.Request) {
	if request != nil && request.Body != nil {
		_ = request.Body.Close()
	}
}

func closeSDKResponseBody(response *http.Response) {
	if response != nil && response.Body != nil {
		_ = response.Body.Close()
	}
}

func authoritativeSDKHTTPResult(ctx context.Context, response *http.Response, err error) (*http.Response, error) {
	if err != nil {
		closeSDKResponseBody(response)
		return nil, err
	}
	if contextErr := completedSDKContextError(ctx); contextErr != nil {
		closeSDKResponseBody(response)
		return nil, contextErr
	}
	if response == nil || response.Body == nil {
		closeSDKResponseBody(response)
		return nil, errInvalidHTTPResponse
	}
	return response, nil
}

func PublishedOperations() []Operation {
	return append([]Operation(nil), publishedOperations[:]...)
}

type Envelope struct {
	Code int             `json:"code"`
	Data json.RawMessage `json:"data"`
	Msg  string          `json:"msg"`
}

type ErrorEnvelope struct {
	Code int             `json:"code"`
	Data json.RawMessage `json:"data"`
	Msg  string          `json:"msg"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type BrowserSessionInfo struct {
	SessionId  string  `json:"sessionId"`
	CreatedAt  string  `json:"createdAt"`
	ExpiresAt  string  `json:"expiresAt"`
	DeviceName *string `json:"deviceName,omitempty"`
}

type BrowserSessionDeviceNameRequest struct {
	DeviceName string `json:"deviceName"`
}

type BrowserSessionListEnvelope struct {
	Code int                  `json:"code"`
	Data []BrowserSessionInfo `json:"data"`
	Msg  string               `json:"msg"`
}

type ProfileRequest struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	Age   int    `json:"age"`
}

type ProjectDescriptionRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	Audience string  `json:"audience"`
}

func WithHTTPClient(httpClient HTTPClient) ClientOption {
	return func(client *Client) error {
		if httpClient == nil {
			return errors.New("goexample SDK HTTP client cannot be nil")
		}
		client.httpClient = httpClient
		return nil
	}
}

func WithMaxResponseBytes(maxResponseBytes int64) ClientOption {
	return func(client *Client) error {
		if maxResponseBytes <= 0 || maxResponseBytes > 64<<20 {
			return errors.New("goexample SDK response size limit must be between 1 byte and 64 MiB")
		}
		client.maxResponseBytes = maxResponseBytes
		return nil
	}
}

func WithRequestEditor(editor RequestEditorFn) ClientOption {
	return func(client *Client) error {
		if editor == nil {
			return errors.New("goexample SDK request editor cannot be nil")
		}
		client.requestEditors = append(client.requestEditors, editor)
		return nil
	}
}

func NewClient(server string, options ...ClientOption) (*Client, error) {
	server = strings.TrimSpace(server)
	baseURL, err := url.Parse(server)
	if err != nil || baseURL.Host == "" || (baseURL.Scheme != "http" && baseURL.Scheme != "https") {
		return nil, errors.New("goexample SDK server must be an absolute HTTP(S) URL")
	}
	if baseURL.User != nil || baseURL.RawQuery != "" || baseURL.Fragment != "" {
		return nil, errors.New("goexample SDK server cannot contain credentials, query, or fragment")
	}
	baseURL.Path = strings.TrimRight(baseURL.Path, "/")
	client := &Client{
		baseURL:          baseURL,
		httpClient:       defaultSDKHTTPClient,
		maxResponseBytes: DefaultMaxResponseBytes,
	}
	for _, option := range options {
		if option == nil {
			return nil, errors.New("goexample SDK client option cannot be nil")
		}
		if err := option(client); err != nil {
			return nil, err
		}
	}
	return client, nil
}

func (response *Response) DecodeJSON(target any) error {
	if response == nil {
		return errors.New("goexample SDK response cannot be nil")
	}
	if target == nil {
		return errors.New("goexample SDK JSON target cannot be nil")
	}
	if err := json.Unmarshal(response.Body, target); err != nil {
		return fmt.Errorf("decode goexample SDK response: %w", err)
	}
	return nil
}

func (response *Response) DecodeEnvelope() (Envelope, error) {
	var envelope Envelope
	err := response.DecodeJSON(&envelope)
	return envelope, err
}

func (c *Client) do(ctx context.Context, method, routePath string, query url.Values, body any, editors []RequestEditorFn) (*Response, error) {
	if ctx == nil {
		return nil, errors.New("goexample SDK request context cannot be nil")
	}
	if contextErr := completedSDKContextError(ctx); contextErr != nil {
		return nil, fmt.Errorf("execute goexample SDK request: %w", contextErr)
	}
	endpoint := *c.baseURL
	escapedPath := c.baseURL.EscapedPath() + routePath
	decodedPath, err := url.PathUnescape(escapedPath)
	if err != nil {
		return nil, fmt.Errorf("build goexample SDK request path: %w", err)
	}
	endpoint.Path = decodedPath
	endpoint.RawPath = escapedPath
	endpoint.RawQuery = query.Encode()
	var requestBody io.Reader = http.NoBody
	if body != nil {
		encodedBody, err := json.Marshal(body)
		if err != nil {
			return nil, fmt.Errorf("encode goexample SDK request: %w", err)
		}
		requestBody = bytes.NewReader(encodedBody)
	}
	request, err := http.NewRequestWithContext(ctx, method, endpoint.String(), requestBody)
	if err != nil {
		return nil, fmt.Errorf("create goexample SDK request: %w", err)
	}
	request.Header.Set("Accept", "application/json")
	if body != nil {
		request.Header.Set("Content-Type", "application/json")
	}
	for _, editor := range append(append([]RequestEditorFn{}, c.requestEditors...), editors...) {
		if editor == nil {
			closeSDKRequestBody(request)
			return nil, errors.New("goexample SDK request editor cannot be nil")
		}
		if contextErr := completedSDKContextError(ctx); contextErr != nil {
			closeSDKRequestBody(request)
			return nil, fmt.Errorf("execute goexample SDK request: %w", contextErr)
		}
		if err := editor(ctx, request); err != nil {
			closeSDKRequestBody(request)
			return nil, fmt.Errorf("edit goexample SDK request: %w", err)
		}
		if contextErr := completedSDKContextError(ctx); contextErr != nil {
			closeSDKRequestBody(request)
			return nil, fmt.Errorf("execute goexample SDK request: %w", contextErr)
		}
	}
	if contextErr := completedSDKContextError(ctx); contextErr != nil {
		closeSDKRequestBody(request)
		return nil, fmt.Errorf("execute goexample SDK request: %w", contextErr)
	}
	httpResponse, err := c.httpClient.Do(request)
	httpResponse, err = authoritativeSDKHTTPResult(ctx, httpResponse, err)
	if err != nil {
		return nil, fmt.Errorf("execute goexample SDK request: %w", err)
	}
	defer httpResponse.Body.Close()
	responseBody, err := io.ReadAll(io.LimitReader(httpResponse.Body, c.maxResponseBytes+1))
	if err != nil {
		return nil, fmt.Errorf("read goexample SDK response: %w", err)
	}
	if int64(len(responseBody)) > c.maxResponseBytes {
		return nil, ErrResponseTooLarge
	}
	if contextErr := completedSDKContextError(ctx); contextErr != nil {
		return nil, fmt.Errorf("execute goexample SDK request: %w", contextErr)
	}
	responseHeader := httpResponse.Header.Clone()
	if contextErr := completedSDKContextError(ctx); contextErr != nil {
		return nil, fmt.Errorf("execute goexample SDK request: %w", contextErr)
	}
	httpResponse.Body = io.NopCloser(bytes.NewReader(responseBody))
	return &Response{
		StatusCode:   httpResponse.StatusCode,
		Header:       responseHeader,
		Body:         responseBody,
		HTTPResponse: httpResponse,
	}, nil
}

func (c *Client) GetServiceIndex(ctx context.Context, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/"
	query := make(url.Values)
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

func (c *Client) GetPrometheusMetrics(ctx context.Context, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/metrics"
	query := make(url.Values)
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

func (c *Client) GetLiveness(ctx context.Context, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/livez"
	query := make(url.Values)
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

func (c *Client) GetReadiness(ctx context.Context, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/readyz"
	query := make(url.Values)
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

func (c *Client) GetStartup(ctx context.Context, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/startupz"
	query := make(url.Values)
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

// Deprecated: GET /api/health is retained only for the published migration window.
func (c *Client) GetApiLiveness(ctx context.Context, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/health"
	query := make(url.Values)
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

// Deprecated: GET /api/health/ready is retained only for the published migration window.
func (c *Client) GetApiReadiness(ctx context.Context, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/health/ready"
	query := make(url.Values)
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

// Deprecated: GET /api/health/startup is retained only for the published migration window.
func (c *Client) GetApiStartup(ctx context.Context, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/health/startup"
	query := make(url.Values)
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

func (c *Client) GetSystemInfo(ctx context.Context, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/system/info"
	query := make(url.Values)
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

func (c *Client) Login(ctx context.Context, body LoginRequest, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/v1/auth/login"
	query := make(url.Values)
	return c.do(ctx, http.MethodPost, routePath, query, body, editors)
}

func (c *Client) StartOIDCBrowserAuthorization(ctx context.Context, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/v1/auth/oidc/start"
	query := make(url.Values)
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

type CompleteOIDCBrowserAuthorizationParams struct {
	State string
	Code  *string
	Error *string
}

func (c *Client) CompleteOIDCBrowserAuthorization(ctx context.Context, params CompleteOIDCBrowserAuthorizationParams, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/v1/auth/oidc/callback"
	query := make(url.Values)
	query.Set("state", params.State)
	if params.Code != nil {
		query.Set("code", *params.Code)
	}
	if params.Error != nil {
		query.Set("error", *params.Error)
	}
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

type LogoutOIDCBrowserSessionParams struct {
	XCSRFToken string
}

func (c *Client) LogoutOIDCBrowserSession(ctx context.Context, params LogoutOIDCBrowserSessionParams, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/v1/auth/oidc/logout"
	query := make(url.Values)
	operationEditor := func(_ context.Context, request *http.Request) error {
		request.Header.Set("X-CSRF-Token", params.XCSRFToken)
		return nil
	}
	editors = append([]RequestEditorFn{operationEditor}, editors...)
	return c.do(ctx, http.MethodPost, routePath, query, nil, editors)
}

func (c *Client) ListOIDCBrowserSessions(ctx context.Context, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/v1/auth/oidc/sessions"
	query := make(url.Values)
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

type RevokeAllOIDCBrowserSessionsParams struct {
	XCSRFToken *string
}

func (c *Client) RevokeAllOIDCBrowserSessions(ctx context.Context, params RevokeAllOIDCBrowserSessionsParams, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/v1/auth/oidc/sessions"
	query := make(url.Values)
	operationEditor := func(_ context.Context, request *http.Request) error {
		if params.XCSRFToken != nil {
			request.Header.Set("X-CSRF-Token", *params.XCSRFToken)
		}
		return nil
	}
	editors = append([]RequestEditorFn{operationEditor}, editors...)
	return c.do(ctx, http.MethodDelete, routePath, query, nil, editors)
}

type UpdateOIDCBrowserSessionDeviceNameParams struct {
	SessionId  string
	XCSRFToken *string
}

func (c *Client) UpdateOIDCBrowserSessionDeviceName(ctx context.Context, params UpdateOIDCBrowserSessionDeviceNameParams, body BrowserSessionDeviceNameRequest, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/v1/auth/oidc/sessions/{sessionId}"
	routePath = strings.ReplaceAll(routePath, "{sessionId}", url.PathEscape(params.SessionId))
	query := make(url.Values)
	operationEditor := func(_ context.Context, request *http.Request) error {
		if params.XCSRFToken != nil {
			request.Header.Set("X-CSRF-Token", *params.XCSRFToken)
		}
		return nil
	}
	editors = append([]RequestEditorFn{operationEditor}, editors...)
	return c.do(ctx, http.MethodPatch, routePath, query, body, editors)
}

type RevokeOIDCBrowserSessionParams struct {
	SessionId  string
	XCSRFToken *string
}

func (c *Client) RevokeOIDCBrowserSession(ctx context.Context, params RevokeOIDCBrowserSessionParams, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/v1/auth/oidc/sessions/{sessionId}"
	routePath = strings.ReplaceAll(routePath, "{sessionId}", url.PathEscape(params.SessionId))
	query := make(url.Values)
	operationEditor := func(_ context.Context, request *http.Request) error {
		if params.XCSRFToken != nil {
			request.Header.Set("X-CSRF-Token", *params.XCSRFToken)
		}
		return nil
	}
	editors = append([]RequestEditorFn{operationEditor}, editors...)
	return c.do(ctx, http.MethodDelete, routePath, query, nil, editors)
}

func (c *Client) GetCurrentUser(ctx context.Context, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/v1/auth/me"
	query := make(url.Values)
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

type GetHelloParams struct {
	Name *string
}

func (c *Client) GetHello(ctx context.Context, params GetHelloParams, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/v1/example/hello"
	query := make(url.Values)
	if params.Name != nil {
		query.Set("name", *params.Name)
	}
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

type PostEchoParams struct {
	XIdempotencyKey *string
}

func (c *Client) PostEcho(ctx context.Context, params PostEchoParams, body map[string]any, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/v1/example/echo"
	query := make(url.Values)
	operationEditor := func(_ context.Context, request *http.Request) error {
		if params.XIdempotencyKey != nil {
			request.Header.Set("X-Idempotency-Key", *params.XIdempotencyKey)
		}
		return nil
	}
	editors = append([]RequestEditorFn{operationEditor}, editors...)
	return c.do(ctx, http.MethodPost, routePath, query, body, editors)
}

type ValidateProfileParams struct {
	XIdempotencyKey *string
}

func (c *Client) ValidateProfile(ctx context.Context, params ValidateProfileParams, body ProfileRequest, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/v1/example/validate"
	query := make(url.Values)
	operationEditor := func(_ context.Context, request *http.Request) error {
		if params.XIdempotencyKey != nil {
			request.Header.Set("X-Idempotency-Key", *params.XIdempotencyKey)
		}
		return nil
	}
	editors = append([]RequestEditorFn{operationEditor}, editors...)
	return c.do(ctx, http.MethodPost, routePath, query, body, editors)
}

type GetDelayedResponseParams struct {
	Ms *int
}

func (c *Client) GetDelayedResponse(ctx context.Context, params GetDelayedResponseParams, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/v1/example/delay"
	query := make(url.Values)
	if params.Ms != nil {
		query.Set("ms", strconv.Itoa(*params.Ms))
	}
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

func (c *Client) GetPrivateExample(ctx context.Context, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/v1/example/private"
	query := make(url.Values)
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

func (c *Client) GetProjectInfo(ctx context.Context, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/v1/project"
	query := make(url.Values)
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

type PreviewProjectParams struct {
	Audience      string
	Format        string
	XTenantID     *string
	XClientLocale string
}

func (c *Client) PreviewProject(ctx context.Context, params PreviewProjectParams, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/v1/project/preview/{audience}"
	routePath = strings.ReplaceAll(routePath, "{audience}", url.PathEscape(params.Audience))
	query := make(url.Values)
	query.Set("format", params.Format)
	operationEditor := func(_ context.Context, request *http.Request) error {
		if params.XTenantID != nil {
			request.Header.Set("X-Tenant-ID", *params.XTenantID)
		}
		request.Header.Set("X-Client-Locale", params.XClientLocale)
		return nil
	}
	editors = append([]RequestEditorFn{operationEditor}, editors...)
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

type DescribeProjectParams struct {
	XIdempotencyKey *string
	XCSRFToken      *string
}

func (c *Client) DescribeProject(ctx context.Context, params DescribeProjectParams, body ProjectDescriptionRequest, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/v1/project/describe"
	query := make(url.Values)
	operationEditor := func(_ context.Context, request *http.Request) error {
		if params.XIdempotencyKey != nil {
			request.Header.Set("X-Idempotency-Key", *params.XIdempotencyKey)
		}
		if params.XCSRFToken != nil {
			request.Header.Set("X-CSRF-Token", *params.XCSRFToken)
		}
		return nil
	}
	editors = append([]RequestEditorFn{operationEditor}, editors...)
	return c.do(ctx, http.MethodPost, routePath, query, body, editors)
}
