import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { test } from 'node:test';
import { readProjectManifest, selectProject } from '../../scripts/lib/project-contracts.mjs';
import {
  buildSDKReleaseManifest,
  verifySDKReleaseManifest,
  writeSDKReleaseManifest,
} from '../../scripts/lib/sdk-release.mjs';

const commit = 'a'.repeat(40);

async function makeFixture(t) {
  const root = await mkdtemp(path.join(os.tmpdir(), 'goexample-sdk-release-'));
  t.after(() => rm(root, { recursive: true, force: true }));

  const document = {
    openapi: '3.1.0',
    info: { title: 'Fixture', version: '1.2.3' },
    paths: {
      '/readyz': {
        get: { operationId: 'getReadiness' },
      },
    },
  };
  const source = `${JSON.stringify(document, null, 2)}\n`;
  const sourceHash = createHash('sha256').update(source).digest('hex');
  await mkdir(path.join(root, 'Solutions', 'Fixture'), { recursive: true });
  await mkdir(path.join(root, 'SDK', 'Fixture'), { recursive: true });
  await mkdir(path.join(root, 'docs', 'openapi'), { recursive: true });
  await mkdir(path.join(root, 'contracts'), { recursive: true });
  await writeFile(path.join(root, 'Solutions', 'Fixture', 'go.mod'), 'module example.test/fixture\n', 'utf8');
  await writeFile(path.join(root, 'docs', 'openapi', 'fixture.json'), source, 'utf8');
  await writeFile(
    path.join(root, 'contracts', 'projects.json'),
    `${JSON.stringify({
      version: 1,
      projects: [
        {
          projectPath: 'Solutions/Fixture',
          contract: { repository: 'workspace', ref: 'worktree', document: 'docs/openapi/fixture.json' },
          sdk: { path: 'SDK/Fixture', package: 'fixture' },
        },
      ],
    }, null, 2)}\n`,
    'utf8',
  );
  await writeFile(path.join(root, 'SDK', 'Fixture', 'VERSION'), '1.2.3\n', 'utf8');
  await writeFile(path.join(root, 'SDK', 'Fixture', 'go.mod'), 'module example.test/SDK/Fixture\n', 'utf8');
  await writeFile(
    path.join(root, 'SDK', 'Fixture', 'client.gen.go'),
    `// Code generated by test; DO NOT EDIT.\n// Source SHA-256: ${sourceHash}\n\npackage fixture\n\nconst APIVersion = "1.2.3"\n`,
    'utf8',
  );
  await writeFile(
    path.join(root, 'SDK', 'Fixture', 'README.md'),
    '# Fixture Go SDK\n\nCurrent SDK version: `1.2.3`.\n',
    'utf8',
  );
  await writeFile(
    path.join(root, 'SDK', 'Fixture', 'CHANGELOG.md'),
    '# Changelog\n\n## 1.2.3 - 2026-08-27\n\n- Initial release.\n',
    'utf8',
  );
  return { root, project: selectProject(readProjectManifest(root), 'Fixture') };
}

test('SDK release manifest binds the module, version, contract, and generated artifacts', async (t) => {
  const { root, project } = await makeFixture(t);
  const manifest = buildSDKReleaseManifest(root, project, { sourceCommit: commit });

  assert.equal(manifest.modulePath, 'example.test/SDK/Fixture');
  assert.equal(manifest.sdkVersion, '1.2.3');
  assert.equal(manifest.expectedTag, 'SDK/Fixture/v1.2.3');
  assert.equal(manifest.publication, 'not_checked');
  assert.equal(manifest.openapi.operationCount, 1);
  assert.deepEqual(manifest.openapi.operations, [
    { operationId: 'getReadiness', method: 'GET', path: '/readyz', deprecated: false },
  ]);
  assert.match(manifest.openapi.sha256, /^[a-f0-9]{64}$/);
  assert.match(manifest.artifacts.generatedClient.sha256, /^[a-f0-9]{64}$/);

  writeSDKReleaseManifest(root, project, manifest);
  assert.doesNotThrow(() => verifySDKReleaseManifest(root, project, manifest));
});

test('SDK release manifest rejects mismatched versions and missing release documentation', async (t) => {
  const { root, project } = await makeFixture(t);
  await writeFile(path.join(root, 'SDK', 'Fixture', 'VERSION'), '1.2.4\n', 'utf8');
  assert.throws(
    () => buildSDKReleaseManifest(root, project, { sourceCommit: commit }),
    /does not match OpenAPI/,
  );

  await writeFile(path.join(root, 'SDK', 'Fixture', 'VERSION'), '1.2.3\n', 'utf8');
  await rm(path.join(root, 'SDK', 'Fixture', 'README.md'));
  assert.throws(
    () => buildSDKReleaseManifest(root, project, { sourceCommit: commit }),
    /README is missing/,
  );
});

test('SDK release manifest verification detects manifest tampering', async (t) => {
  const { root, project } = await makeFixture(t);
  const manifest = buildSDKReleaseManifest(root, project, { sourceCommit: commit });
  writeSDKReleaseManifest(root, project, manifest);
  await writeFile(path.join(root, 'SDK', 'Fixture', 'release-manifest.json'), '{"schemaVersion":1}\n', 'utf8');

  assert.throws(
    () => verifySDKReleaseManifest(root, project, manifest),
    /is stale or has been modified/,
  );
});
