// Code generated by scripts/go-sdk.mjs; DO NOT EDIT.
// Source: docs/openapi/billing.json
// Source SHA-256: b20646e824a97cc194ad017022276886ecebc5a114c930805ccb2ba29b96f2e0

package billing

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strconv"
	"strings"
)

const APIVersion = "1.0.0"
const DefaultMaxResponseBytes int64 = 1 << 20

var ErrResponseTooLarge = errors.New("goexample SDK response exceeds configured size limit")

type HTTPClient interface {
	Do(*http.Request) (*http.Response, error)
}

type RequestEditorFn func(context.Context, *http.Request) error
type ClientOption func(*Client) error

type Client struct {
	baseURL          *url.URL
	httpClient       HTTPClient
	maxResponseBytes int64
	requestEditors   []RequestEditorFn
}

type Operation struct {
	OperationID string
	Method      string
	Path        string
	Deprecated  bool
}

var publishedOperations = [...]Operation{
	{OperationID: "getServiceInfo", Method: "GET", Path: "/", Deprecated: false},
	{OperationID: "getMetrics", Method: "GET", Path: "/metrics", Deprecated: false},
	{OperationID: "getLegacyHealth", Method: "GET", Path: "/api/health", Deprecated: true},
	{OperationID: "getLegacyReadiness", Method: "GET", Path: "/api/health/ready", Deprecated: true},
	{OperationID: "getLegacyStartup", Method: "GET", Path: "/api/health/startup", Deprecated: true},
	{OperationID: "getSystemInfo", Method: "GET", Path: "/api/system/info", Deprecated: false},
	{OperationID: "getLiveness", Method: "GET", Path: "/livez", Deprecated: false},
	{OperationID: "getReadiness", Method: "GET", Path: "/readyz", Deprecated: false},
	{OperationID: "getStartup", Method: "GET", Path: "/startupz", Deprecated: false},
	{OperationID: "getExampleHello", Method: "GET", Path: "/api/v1/example/hello", Deprecated: false},
	{OperationID: "postExampleEcho", Method: "POST", Path: "/api/v1/example/echo", Deprecated: false},
	{OperationID: "postExampleValidate", Method: "POST", Path: "/api/v1/example/validate", Deprecated: false},
	{OperationID: "getExampleDelay", Method: "GET", Path: "/api/v1/example/delay", Deprecated: false},
	{OperationID: "getBillingSummary", Method: "GET", Path: "/api/v1/billing/summary", Deprecated: false},
}

type Response struct {
	StatusCode   int
	Header       http.Header
	Body         []byte
	HTTPResponse *http.Response
}

func PublishedOperations() []Operation {
	return append([]Operation(nil), publishedOperations[:]...)
}

type Envelope struct {
	Code int            `json:"code"`
	Data map[string]any `json:"data"`
	Msg  string         `json:"msg"`
}

type EchoRequest = map[string]any

type ProfileRequest struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	Age   *int   `json:"age,omitempty"`
}

func WithHTTPClient(httpClient HTTPClient) ClientOption {
	return func(client *Client) error {
		if httpClient == nil {
			return errors.New("goexample SDK HTTP client cannot be nil")
		}
		client.httpClient = httpClient
		return nil
	}
}

func WithMaxResponseBytes(maxResponseBytes int64) ClientOption {
	return func(client *Client) error {
		if maxResponseBytes <= 0 || maxResponseBytes > 64<<20 {
			return errors.New("goexample SDK response size limit must be between 1 byte and 64 MiB")
		}
		client.maxResponseBytes = maxResponseBytes
		return nil
	}
}

func WithRequestEditor(editor RequestEditorFn) ClientOption {
	return func(client *Client) error {
		if editor == nil {
			return errors.New("goexample SDK request editor cannot be nil")
		}
		client.requestEditors = append(client.requestEditors, editor)
		return nil
	}
}

func NewClient(server string, options ...ClientOption) (*Client, error) {
	server = strings.TrimSpace(server)
	baseURL, err := url.Parse(server)
	if err != nil || baseURL.Host == "" || (baseURL.Scheme != "http" && baseURL.Scheme != "https") {
		return nil, errors.New("goexample SDK server must be an absolute HTTP(S) URL")
	}
	if baseURL.User != nil || baseURL.RawQuery != "" || baseURL.Fragment != "" {
		return nil, errors.New("goexample SDK server cannot contain credentials, query, or fragment")
	}
	baseURL.Path = strings.TrimRight(baseURL.Path, "/")
	client := &Client{
		baseURL:          baseURL,
		httpClient:       http.DefaultClient,
		maxResponseBytes: DefaultMaxResponseBytes,
	}
	for _, option := range options {
		if option == nil {
			return nil, errors.New("goexample SDK client option cannot be nil")
		}
		if err := option(client); err != nil {
			return nil, err
		}
	}
	return client, nil
}

func (response *Response) DecodeJSON(target any) error {
	if response == nil {
		return errors.New("goexample SDK response cannot be nil")
	}
	if target == nil {
		return errors.New("goexample SDK JSON target cannot be nil")
	}
	if err := json.Unmarshal(response.Body, target); err != nil {
		return fmt.Errorf("decode goexample SDK response: %w", err)
	}
	return nil
}

func (response *Response) DecodeEnvelope() (Envelope, error) {
	var envelope Envelope
	err := response.DecodeJSON(&envelope)
	return envelope, err
}

func (c *Client) do(ctx context.Context, method, routePath string, query url.Values, body any, editors []RequestEditorFn) (*Response, error) {
	if ctx == nil {
		return nil, errors.New("goexample SDK request context cannot be nil")
	}
	endpoint := *c.baseURL
	escapedPath := c.baseURL.EscapedPath() + routePath
	decodedPath, err := url.PathUnescape(escapedPath)
	if err != nil {
		return nil, fmt.Errorf("build goexample SDK request path: %w", err)
	}
	endpoint.Path = decodedPath
	endpoint.RawPath = escapedPath
	endpoint.RawQuery = query.Encode()
	var requestBody io.Reader = http.NoBody
	if body != nil {
		encodedBody, err := json.Marshal(body)
		if err != nil {
			return nil, fmt.Errorf("encode goexample SDK request: %w", err)
		}
		requestBody = bytes.NewReader(encodedBody)
	}
	request, err := http.NewRequestWithContext(ctx, method, endpoint.String(), requestBody)
	if err != nil {
		return nil, fmt.Errorf("create goexample SDK request: %w", err)
	}
	request.Header.Set("Accept", "application/json")
	if body != nil {
		request.Header.Set("Content-Type", "application/json")
	}
	for _, editor := range append(append([]RequestEditorFn{}, c.requestEditors...), editors...) {
		if editor == nil {
			return nil, errors.New("goexample SDK request editor cannot be nil")
		}
		if err := editor(ctx, request); err != nil {
			return nil, fmt.Errorf("edit goexample SDK request: %w", err)
		}
	}
	httpResponse, err := c.httpClient.Do(request)
	if err != nil {
		return nil, fmt.Errorf("execute goexample SDK request: %w", err)
	}
	defer httpResponse.Body.Close()
	responseBody, err := io.ReadAll(io.LimitReader(httpResponse.Body, c.maxResponseBytes+1))
	if err != nil {
		return nil, fmt.Errorf("read goexample SDK response: %w", err)
	}
	if int64(len(responseBody)) > c.maxResponseBytes {
		return nil, ErrResponseTooLarge
	}
	httpResponse.Body = io.NopCloser(bytes.NewReader(responseBody))
	return &Response{
		StatusCode:   httpResponse.StatusCode,
		Header:       httpResponse.Header.Clone(),
		Body:         responseBody,
		HTTPResponse: httpResponse,
	}, nil
}

func (c *Client) GetServiceInfo(ctx context.Context, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/"
	query := make(url.Values)
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

func (c *Client) GetMetrics(ctx context.Context, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/metrics"
	query := make(url.Values)
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

// Deprecated: GET /api/health is retained only for the published migration window.
func (c *Client) GetLegacyHealth(ctx context.Context, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/health"
	query := make(url.Values)
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

// Deprecated: GET /api/health/ready is retained only for the published migration window.
func (c *Client) GetLegacyReadiness(ctx context.Context, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/health/ready"
	query := make(url.Values)
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

// Deprecated: GET /api/health/startup is retained only for the published migration window.
func (c *Client) GetLegacyStartup(ctx context.Context, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/health/startup"
	query := make(url.Values)
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

func (c *Client) GetSystemInfo(ctx context.Context, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/system/info"
	query := make(url.Values)
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

func (c *Client) GetLiveness(ctx context.Context, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/livez"
	query := make(url.Values)
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

func (c *Client) GetReadiness(ctx context.Context, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/readyz"
	query := make(url.Values)
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

func (c *Client) GetStartup(ctx context.Context, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/startupz"
	query := make(url.Values)
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

type GetExampleHelloParams struct {
	Name *string
}

func (c *Client) GetExampleHello(ctx context.Context, params GetExampleHelloParams, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/v1/example/hello"
	query := make(url.Values)
	if params.Name != nil {
		query.Set("name", *params.Name)
	}
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

func (c *Client) PostExampleEcho(ctx context.Context, body EchoRequest, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/v1/example/echo"
	query := make(url.Values)
	return c.do(ctx, http.MethodPost, routePath, query, body, editors)
}

func (c *Client) PostExampleValidate(ctx context.Context, body ProfileRequest, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/v1/example/validate"
	query := make(url.Values)
	return c.do(ctx, http.MethodPost, routePath, query, body, editors)
}

type GetExampleDelayParams struct {
	Ms *int
}

func (c *Client) GetExampleDelay(ctx context.Context, params GetExampleDelayParams, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/v1/example/delay"
	query := make(url.Values)
	if params.Ms != nil {
		query.Set("ms", strconv.Itoa(*params.Ms))
	}
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}

func (c *Client) GetBillingSummary(ctx context.Context, editors ...RequestEditorFn) (*Response, error) {
	routePath := "/api/v1/billing/summary"
	query := make(url.Values)
	return c.do(ctx, http.MethodGet, routePath, query, nil, editors)
}
